"""
components/dispatch_panel.py – Prescriptive Fleet Rebalancing Dispatch Panel
=============================================================================
Displays operational transfer recommendations generated by spatial Haversine
matching between high-deficit and high-surplus stations in the same metro cluster.
"""

from __future__ import annotations

from dash import html


def render_dispatch_panel(pairs: list[dict] | None = None) -> html.Div:
    """
    Render the Smart Fleet Rebalancing dispatch panel card.

    Parameters
    ----------
    pairs : list[dict], optional
        List of rebalancing pair dictionaries from compute_smart_dispatch_pairs().

    Returns
    -------
    html.Div
    """
    header = html.Div(
        className="mb-4",
        children=[
            html.Div(
                style={"display": "flex", "alignItems": "center", "gap": "8px", "marginBottom": "6px"},
                children=[
                    html.Span("PRESCRIPTIVE DISPATCH", className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-teal-100 text-teal-800 uppercase tracking-wider"),
                    html.Span("Automated Spatial Match", className="text-xs text-slate-400 font-medium"),
                ],
            ),
            html.H3("Smart Fleet Rebalancing Recommendations", className="text-base sm:text-lg font-bold text-slate-900"),
            html.P(
                "Algorithmic rebalancing pairs high-deficit stations with their nearest high-surplus neighbor within the same metropolitan cluster using Haversine distance.",
                className="text-xs text-slate-500 mt-0.5",
            ),
        ],
    )

    if not pairs:
        content = html.Div(
            className="dispatch-empty",
            children=[
                html.Span("✅", style={"fontSize": "24px", "display": "block", "marginBottom": "8px"}),
                html.P(
                    "Network is well balanced or no severe deficit-surplus pairs exceed threshold in the current filter selection.",
                    style={"color": "#94A3B8", "margin": 0, "fontSize": "13px"},
                ),
            ],
        )
    else:
        card_items = []
        for idx, p in enumerate(pairs):
            deficit_stn = p["deficit_station"]
            surplus_stn = p["surplus_station"]
            transfer_qty = p["recommended_transfer"]
            dist_km = p["distance_km"]
            region = p["region"]
            deficit_amt = p["deficit_amount"]
            surplus_amt = p["surplus_amount"]

            item = html.Div(
                className="dispatch-pair-card",
                children=[
                    # Top line: Region and Distance
                    html.Div(
                        className="dispatch-pair-header",
                        children=[
                            html.Span(f"Pair #{idx + 1} · {region}", className="dispatch-pair-title"),
                            html.Span(f"📍 {dist_km:.2f} km apart", className="dispatch-distance-badge"),
                        ],
                    ),

                    # Middle: Source -> Transfer -> Destination
                    html.Div(
                        className="dispatch-flow-row",
                        children=[
                            # Source (Surplus)
                            html.Div(
                                className="dispatch-node surplus-node",
                                children=[
                                    html.Span("SURPLUS SOURCE", className="dispatch-node-type"),
                                    html.Span(surplus_stn, className="dispatch-node-name"),
                                    html.Span(f"+{surplus_amt:,} net arrivals", className="dispatch-node-stat"),
                                ],
                            ),

                            # Transfer arrow & recommendation
                            html.Div(
                                className="dispatch-transfer-arrow",
                                children=[
                                    html.Span(f"Transfer ~{transfer_qty} bikes", className="dispatch-transfer-pill"),
                                    html.Div(className="arrow-line-wrapper", children=[
                                        html.Span("➔", className="dispatch-arrow-symbol"),
                                    ]),
                                ],
                            ),

                            # Destination (Deficit)
                            html.Div(
                                className="dispatch-node deficit-node",
                                children=[
                                    html.Span("DEFICIT TARGET", className="dispatch-node-type"),
                                    html.Span(deficit_stn, className="dispatch-node-name"),
                                    html.Span(f"-{deficit_amt:,} net departures", className="dispatch-node-stat"),
                                ],
                            ),
                        ],
                    ),
                ],
            )
            card_items.append(item)

        content = html.Div(className="dispatch-pair-list", children=card_items)

    return html.Div(
        className="bg-white rounded-xl border border-slate-200 shadow-sm p-4 sm:p-5 flex flex-col justify-between mb-8",
        children=[
            header,
            content,
        ],
    )
